// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: ht11prep

#ifndef _HT11PREP_UI_H
#define _HT11PREP_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_tempLabel;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_serverStatusLabel;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Arc1;
extern lv_obj_t * uic_tempLabel;
extern lv_obj_t * uic_Label3;
extern lv_obj_t * uic_serverStatusLabel;
extern lv_obj_t * uic_Label1;
extern lv_obj_t * uic_Label5;

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
